# port
server:
  port: 8080

# scan beans
mybatis:
  type-aliases-package: com.learn.provider_service.bean
  # mapper.xml path
  mapper-locations: classpath:mappers/*Mapper.xml

# database info
spring:
  datasource:
    data-username: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/test?setUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  #redis config
  redis:
    host: localhost
    port: 6379
  #server id
  application:
    name: provider-service

#connfig Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30       # heartbeat time
    lease-expiration-duration-in-seconds: 90    # expiration time


