server:
  port: 10086
spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false           # catch register list
    register-with-eureka: false     # register self
  server:
    enable-self-preservation: false # close self preservation
    eviction-interval-timer-in-ms: 90 # delete service time



