# port
server:
  port: ${port:8080}

# scan beans
mybatis:
  type-aliases-package: com.learn.provider_service.entity
  # mapper.xml path
  mapper-locations: classpath:mappers/*Mapper.xml

# database info
spring:
  datasource:
    data-username: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/test?setUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  #redis config
  redis:
    host: localhost
    port: 6379
  #server id
  application:
    name: provider-service

  #JPA
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update #每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      naming:
        #默认命名策略：直接映射，不会做过多的处理（前提没有设置@Table，@Column等属性的时候）
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        # 回滚,tripped before adding them to the entity manager
        dialect: org.hibernate.dialect.MySQL5Dialect

  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672    #默认端口，web界面: localhost:15672
    username: guest
    password: guest

#connfig Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30       # heartbeat time
    lease-expiration-duration-in-seconds: 90    # expiration time

