server:
  port: 8082

spring:
  application:
    name: consumer-service

#connfig Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30       # heartbeat time
    lease-expiration-duration-in-seconds: 90    # expiration time

# ribbon method
provider-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule  #默认

# 配置熔断策略-会找不到但是起作用：
hystrix:
  command:
    default:
      circuitBreaker:
        # 原理分析中解释配置含义 # 强制打开熔断器 默认false关闭的。测试配置是否生效
        forceOpen: false
        # 触发熔断错误比例阈值，默认值50%
        errorThresholdPercentage: 50
        # 熔断后休眠时长，默认值5秒
        sleepWindowInMilliseconds: 5000
        # 熔断触发最小请求次数，默认值是20
        requestVolumeThreshold: 10
      execution:
        isolation:
          thread:
            # 熔断超时设置，默认为1秒
            timeoutInMilliseconds: 2000